### ISSUE TITLE
[Bug] When "Watch Later" list is open this script will press the loop button on that instead

### ISSUE THREAD

**Issue by DarkVamprism** [HatScripts/YouTubeAutoLiker#1]
Using the script as is causes the "Loop Playlist" button to be pressed rather than the like button, changing the line
`LIKE_BUTTON:         '#top-level-buttons > ytd-toggle-button-renderer:nth-child(1), .like-button-renderer-like-button:not(.hid)',`
to
`LIKE_BUTTON:         'ytd-video-primary-info-renderer #top-level-buttons > ytd-toggle-button-renderer:nth-child(1), .like-button-renderer-like-button:not(.hid)',`

fixes this issue

P.S Thank you for making this script, I have been looking for a working auto-like script for ages.

**Comment by HatScripts** [comment]
Hi, thanks for the bug report. I just confirmed that this bug occurs in the new YouTube layout when watching a playlist, and that your proposed change fixes the issue.

The reason for this occuring is because of an issue with Chrome DevTools. I believe right-clicking an element and selecting `Copy` -> `Copy selector` should technically always copy the *unique* selector for that element, however it seems to make the assumption that IDs will never be used more than once on the page—and [according to the HTML spec](https://softwareengineering.stackexchange.com/a/127180) they shouldn't be—but of course this is not always the case.

Anyway, I'll create a PR now to implement your proposed change. Thanks again!

P.S. I'm glad to see somebody (other than myself 😋) getting use out of the script. I wasn't sure how popular it would be, but the now-defunct script it's based on seemed to be quite popular before it stopped working.
